---
- name: Установка и настройка zabbix (серверная часть)
  hosts: zabbix_server
  gather_facts: no
  vars:
    db_host_cloud: c-{{ pg_cluster_id }}.rw.mdb.yandexcloud.net  
    db_port_cloud: 6432
    db_name_cloud: "{{ db_name_local }}"
    db_user_cloud: "{{ db_user_local }}"
    db_password_cloud: "{{ db_password_local }}"
  become: yes
  tasks:

  - name: Проверка доступности
    ping:

  - name: Обновление системы и установка зависимостей
    apt:
      update_cache: yes
      name: ['wget', 'curl', 'postgresql-contrib', 'mc']
      state: present

  - name: Копирование установочного пакета zabbix репозитория
    copy:
      src: packages/{{ pkg_zabbix }}
      dest: /tmp/

  - name: Установка zabbix репозитория
    command: dpkg -i /tmp/{{ pkg_zabbix }}

  - name: Обновление кеша установщика
    apt:
      update_cache: yes

  - name: Установка Zabbix Server и необходимых компонентов
    apt:
      name: ['zabbix-server-pgsql', 'zabbix-agent', 'zabbix-sql-scripts']
      state: present

 
  - name: Копируем файл внутри удаленной машины
    copy:
      src: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz
      dest: /tmp/server.sql.gz


  - name : Распаковываем server.sql.gz 
    shell:
      cmd: |
        cd /tmp
        zcat server.sql.gz >  server.sql

  - name: "Ansible | Print a variable"
    debug:
      msg: "Использован кластер облачной yandex-cloud со следующими настройками Хост = {{ db_host_cloud }}, имя базы данных = {{ db_name_cloud }},  пользователь базы= {{ db_user_cloud }}, пароль базы = {{ db_password_cloud }}, db_port = {{db_port_cloud}}"

  - name: Загружаем начальные данные в базу zabbix
    community.postgresql.postgresql_db:
        name: "{{ db_name_cloud }}"
        login_host: "{{ db_host_cloud }}"
        login_password: "{{db_password_cloud}}"
        login_user: "{{ db_user_cloud }}"
        port: "{{db_port_cloud}}"
        state: restore
        target: /tmp/server.sql.gz
    become: yes


  - name: Копирование файла конфигурации Zabbix Server
    template:
      src: templates/zabbix_server.conf.j2
      dest: /etc/zabbix/zabbix_server.conf
      mode: 0644

  - name: Установка пароля базы данных в конфигурационном файле Zabbix
    lineinfile:
      dest: /etc/zabbix/zabbix_server.conf
      regexp: '^# DBPassword='
      line: 'DBPassword={{ db_password_cloud }}'

  - name: Перезапуск сервиса Zabbix Server
    systemd:
      name: zabbix-server
      state: restarted
      enabled: yes

  - name: Перезапуск сервиса Zabbix Agent
    systemd:
      name: zabbix-agent
      state: restarted
      enabled: yes


