

- name: Установка и настройка Zabbix (веб-часть)
  hosts: zabbix_web_server
  gather_facts: no
  vars:
    db_host_cloud: c-{{ pg_cluster_id }}.rw.mdb.yandexcloud.net  
    db_port_cloud: 6432
    db_name_cloud: "{{ db_name_local }}"
    db_user_cloud: "{{ db_user_local }}"
    db_password_cloud: "{{ db_password_local }}"
  become: yes
  tasks:

  - name: Обновление кеш
    apt:
      update_cache: yes

  - name: Копирование установочного пакета zabbix репозитория
    copy:
      src: packages/{{ pkg_zabbix }}
      dest: /tmp/

  - name: Установка zabbix репозитория
    command: dpkg -i /tmp/{{ pkg_zabbix }}

  - name: Обновление кеша установщика
    apt:
      update_cache: yes

  - name: Обновление системы и установка зависимостей для веб-части
    apt:
      update_cache: yes
      name: ['mc', 'wget', 'curl', 'nginx', 'php-fpm', 'php-pgsql', 'php-bcmath', 'php-mbstring', 'php-gd', 'php-xml', 'zabbix-frontend-php', 'zabbix-nginx-conf', 'zabbix-server-pgsql','zabbix-agent', 'zabbix-sql-scripts', 'zabbix-server-pgsql']
      state: present

  - name : Очищаем файл настроек web интерйейса zabbix.conf.php
    shell:
      cmd: |
        echo -n > /etc/zabbix/web/zabbix.conf.php



  - name: Генеририуем соержимое файла настроек web интерфейса /etc/zabbix/web/zabbix.conf.php
    become: yes
    blockinfile:
        path: /etc/zabbix/web/zabbix.conf.php
        block: |
         <?php
         // Zabbix GUI configuration file.

          $DB['TYPE']				= 'POSTGRESQL';
          $DB['SERVER']			= '{{ db_host_cloud }}';
          $DB['PORT']			= '{{ db_port_cloud }}';
          $DB['DATABASE']		= '{{ db_name_cloud }}';
          $DB['USER']			= '{{ db_user_cloud }}';
          $DB['PASSWORD']		= '{{ db_password_cloud }}';

          // Schema name. Used for PostgreSQL.
          $DB['SCHEMA']			= '';

          // Used for TLS connection.
          $DB['ENCRYPTION']		= false;
          $DB['KEY_FILE']			= '';
          $DB['CERT_FILE']		= '';
          $DB['CA_FILE']			= '';
          $DB['VERIFY_HOST']		= false;
          $DB['CIPHER_LIST']		= '';

          // Vault configuration. Used if database credentials are stored in Vault secrets manager.
          $DB['VAULT_URL']		= '';
          $DB['VAULT_DB_PATH']	= '';
          $DB['VAULT_TOKEN']		= '';

          // Use IEEE754 compatible value range for 64-bit Numeric (float) history values.
          // This option is enabled by default for new Zabbix installations.
          // For upgraded installations, please read database upgrade notes before enabling this option.
          $DB['DOUBLE_IEEE754']	= true;

          // Uncomment and set to desired values to override Zabbix hostname/IP and port.
          // $ZBX_SERVER			= '';
          // $ZBX_SERVER_PORT		= '';

          $ZBX_SERVER_NAME		= 'my-zabbix-cloud';

          $IMAGE_FORMAT_DEFAULT	= IMAGE_FORMAT_PNG;
 

  - name: Настройка PHP для Zabbix
    blockinfile:
      path: /etc/php/8.1/fpm/php.ini
      block: |
        post_max_size = 16M
        upload_max_filesize = 2M
        max_execution_time = 300
        max_input_time = 300
        memory_limit = 128M
        date.timezone = Europe/Moscow

  
  - name : Очищаем файл настроек /etc/nginx/conf.d/zabbix.conf
    shell:
      cmd: |
        echo -n > /etc/nginx/conf.d/zabbix.conf

  - name: Настроиваем  Nginx для Zabbix /etc/nginx/conf.d/zabbix.conf
    blockinfile:
      path: /etc/nginx/conf.d/zabbix.conf
      block: |
          server {
              listen 80;
              server_name  {{ server_name }};

              root /usr/share/zabbix;

              index index.php index.html index.htm;

              location / {
                  try_files $uri $uri/ =404;
              }

              location ~ \.php$ {
                  fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  include fastcgi_params;
              }

              location ~ /\.ht {
                  deny all;
              }
          }

  - name: Перезапуск сервисов Nginx и PHP-FPM
    systemd:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - nginx
      - php8.1-fpm

  - name: Печать адреса сервера zabbix
    ansible.builtin.debug:
        msg: "Для работы с zabbix перейдите по адресу http://{{ zabbix_web_ip_address }} логин 'Admin' пароль 'zabbix'"


- name: Установка и настройка zabbix (серверная часть)
  hosts: zabbix_server
  gather_facts: no
  
  become: yes
  tasks:

  - name: Проверка доступности
    ping:

  - name: Перезапуск сервиса Zabbix Server
    systemd:
      name: zabbix-server
      state: restarted
      enabled: yes

  - name: Перезапуск сервиса Zabbix Agent
    systemd:
      name: zabbix-agent
      state: restarted
      enabled: yes
