---
- name: Установка пакетов на web сервера
  hosts: internal_servers
  gather_facts: no
  become: yes
  tasks:
    - name: Обновление кеш
      apt:
        update_cache: yes

    - name: Установка nginx
      apt:
        name: nginx
        state: present

    - name: Копирование страницы index.html на сервера 
      copy:
        src: templates/index.html
        dest: /var/www/html/
    
    - name: перзапуск nginx
      service:
        name: nginx
        state: restarted
    
    - name: Копирование filebeat
      copy:
        src: packages/{{ pkg_name }}
        dest: /tmp/
    
    - name: Установка filebeat .deb
      apt:
        deb: "/tmp/{{ pkg_name }}"
        state: present

    - name: Копирование файла настроек filebeat.yml
      template:
        src: templates/filebeat.yml.j2
        mode: 0644
        dest: /etc/filebeat/filebeat.yml

    - name: Конфигурирование nginx модуля
      copy:
        dest: /etc/filebeat/modules.d/nginx.yml.disabled
        content: |
          - module: nginx
            # Access logs
            access:
              enabled: true

            # Error logs
            error:
              enabled: true
        mode: 0644
     
    - name: Активируе nginx модуль для filebeat
      shell:
        cmd:  filebeat setup --dashboards && filebeat modules enable system nginx
        
    - name: перезапуск демона systemd
      shell:
        cmd: systemctl daemon-reload
    
    - name: Перезапускаемм Filebeat
      systemd:
        name: filebeat.service
        state: restarted
        enabled: true

 
- name: Мониторинг сервера nginx в zabbix
  hosts: internal_servers
  gather_facts: no
  become: yes
  tasks:
    - name: Копируем файл конфигурации stub_status.conf
      template:
        src: templates2/stub_status.conf
        mode: 0644
        dest:  /etc/nginx/conf.d/stub_status.conf

    - name:  Добавляем настройки в /etc/nginx/nginx.conf
      blockinfile:
        path: /etc/nginx/nginx.conf
        marker: "access_log /var/log/nginx/access.log;"
        insertafter: "access_log /var/log/nginx/access.log;"
        block: "{{ lookup('file', 'templates2/nginx.conf') }}"
    
    - name: Убираем строку из error.log
      lineinfile:
        path: /etc/nginx/nginx.conf
        state: absent
        regexp: '^% error_log /var/log/nginx/error.log;'

    - name: Убираем строку из  access.log
      lineinfile:
        path: /etc/nginx/nginx.conf
        state: absent
        regexp: '^%access_log /var/log/nginx/access.log;'

    - name: Перезапускаем nginx
      systemd:
        name: nginx.service
        state: restarted
        enabled: true
     

...

       