- name: Configure zabbix server
  hosts: zabbix_server
  gather_facts: no
  become: yes
  tasks:
  - name: Update cache
    apt:
      update_cache: yes

  - name: Install postgresql
    apt:
      name: postgresql
      state: present

  - name: Copy zabbix package
    copy:
      src: packages/{{ pkg_zabbix }}
      dest: /tmp/

  - name: Install zabbix repository
    command: dpkg -i /tmp/{{ pkg_zabbix }}

  - name: Установка Zabbix 6.0
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop: ["zabbix-server-pgsql", "zabbix-frontend-php", "php8.1-pgsql", "zabbix-nginx-conf", "zabbix-sql-scripts", "zabbix-agent"]

  - name: Create user and DB
    shell:
      cmd: |
        su - postgres -c "psql --command \"CREATE USER {{ zabbix_user }} WITH PASSWORD '{{ zabbix_password }}';\"" && \
        su - postgres -c "psql --command \"CREATE DATABASE zabbix OWNER {{ zabbix_user }};\""          
        
  - name: Import initial schema and data in DB
    shell:
      cmd: |
        zcat packages/{{ zip_zabbix }} | sudo -u {{ zabbix_user }} -p {{ zabbix_password }} psql zabbix

  - name: Copy zabbix_server.conf
    template:
      src: templates/zabbix_server.conf.j2
      mode: 0644
      dest: /etc/zabbix/zabbix_server.conf

  - name: Copy nginx.conf
    template:
      src: templates/nginx.conf.j2
      mode: 0644
      dest: /etc/zabbix/nginx.conf

  - name: Restart services
    systemd:
      name: "{{ item }}"
      state: restarted
      enabled: true
    loop: ["zabbix-server", "zabbix-agent", "nginx", "php8.1-fpm"]

- name: Configure zabbix agent
  hosts: internal_servers
  gather_facts: no
  become: yes
  tasks:
    - name: Copy zabbix package
      copy:
        src: packages/{{ pkg_zabbix }}
        dest: /tmp/

    - name: Install zabbix repository
      command: dpkg -i /tmp/{{ pkg_zabbix }}

    - name: Install zabbix-agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: yes

    - name: Add server IP
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server=127.0.0.1'
        replace: 'Server={{ zabbix_server }}'

    - name: Add server IP
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'ServerActive=127.0.0.1'
        replace: 'ServerActive={{ zabbix_server }}'

    - name: Restart zabbix agent
      systemd:
        name: zabbix-agent
        state: restarted
        enabled: true   