- name: Установка zabbix сервера с испольгованием pgsql кластера yandex cloud
  hosts: zabbix_server
  gather_facts: no
  vars:
    host: c-{{ pg_cluster_id }}.rw.mdb.yandexcloud.net # Укажите адрес хоста
    db_port: 6432                                           # Укажите порт PostgreSQL (по умолчанию 5432)
    db_name: "zabbix"                                       # Укажите имя базы данных
    db_user:  "{{ zabbix_user }}"                           # Укажите пользователя базы данных
    db_password: "{{ pg_admin_password }}"                  # Укажите пароль пользователя базы данных
  become: yes
  tasks:
 
  - name: Обновление системы и установка зависимостей
    apt:
      update_cache: yes
      name: ['wget', 'curl', 'nginx', 'postgresql', 'postgresql-contrib', 'php-fpm', 'php-pgsql', 'php-bcmath', 'php-mbstring', 'php-gd', 'php-xml', 'mc']
      state: present

  - name: Копируем zabbix пакет
    copy:
      src: packages/{{ pkg_zabbix }}
      dest: /tmp/

  - name: Устанавливаем zabbix репозиторий 
    command: dpkg -i /tmp/{{ pkg_zabbix }}

  - name: обновляем кеш системы
    apt:
      update_cache: yes

   
  - name: Установливаем Zabbix Server и компоненты
    become: yes
    apt:
      name: ['zabbix-server-pgsql', 'zabbix-frontend-php', 'zabbix-nginx-conf', 'zabbix-agent', 'zabbix-sql-scripts']
      state: present
 
  - name: Копируем файл внутри удаленной машины
    copy:
      src: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz
      dest: /tmp/server.sql.gz


  - name : Распаковываем server.sql.gz 
    shell:
      cmd: |
        cd /tmp
        zcat server.sql.gz >  server.sql

  - name: Загружаем начальные данные в базу zabbix
    community.postgresql.postgresql_db:
        name: zabbix
        login_host: "{{ host }}"
        login_password: "{{ db_password }}"
        login_user: "{{ db_user }}"
        port: 6432
        state: restore
        target: /tmp/server.sql
    become: yes


  - name: Дамп базы данных поднят удачно
    ansible.builtin.debug:
        msg: "Database imported successfully!"

  - name: "Ansible | Print a variable"
    debug:
      msg: "Использован кластер зпыйд yandex-cloud со следующими настройками db_host = {{ host }}, \n db_name = {{ db_name }}, \n db_user = {{ db_user }}, \n db_password = {{ db_password }},\n db_port = {{db_port}}"

  - name: Копируем файл настроек zabbix сервера zabbix_server.conf
    template:
      src: templates/zabbix_server.conf2.j2
      mode: 0644
      dest: /etc/zabbix/zabbix_server.conf

  - name: Устанавливаем пароль базы данных PostgreSQL
    lineinfile:
       dest: /etc/zabbix/zabbix_server.conf
       regexp: '^# DBPassword='
       line: 'DBPassword={{ db_password }}' 
 
 
  - name: Устанавливаем  адврес хоста кластера yandex cloud PostgreSQL
    lineinfile:
       dest: /etc/zabbix/zabbix_server.conf
       regexp: '# DBHost='
       line: 'DBHost={{ host }}' 

  - name: Устанавливаем порт кластера yandex-cloud PostgreSQL 
    lineinfile:
       dest: /etc/zabbix/zabbix_server.conf
       regexp: '# DBPort='
       line: 'DBPort={{ db_port }}' 

  - name : Очищаем файл настроек web интерйейса zabbix.conf.php
    shell:
      cmd: |
        echo -n > /etc/zabbix/web/zabbix.conf.php


  - name: Генеририуем соержимое йайла настроек web интерфейса /etc/zabbix/web/zabbix.conf.php
    become: yes
    blockinfile:
       path: /etc/zabbix/web/zabbix.conf.php
       block: |
         <?php
         // Zabbix GUI configuration file.

          $DB['TYPE']				= 'POSTGRESQL';
          $DB['SERVER']			= '{{ host }}';
          $DB['PORT']			= '{{ db_port }}';
          $DB['DATABASE']		= '{{ db_name }}';
          $DB['USER']			= '{{ db_user }}';
          $DB['PASSWORD']		= '{{ db_password }}';

          // Schema name. Used for PostgreSQL.
          $DB['SCHEMA']			= '';

          // Used for TLS connection.
          $DB['ENCRYPTION']		= false;
          $DB['KEY_FILE']			= '';
          $DB['CERT_FILE']		= '';
          $DB['CA_FILE']			= '';
          $DB['VERIFY_HOST']		= false;
          $DB['CIPHER_LIST']		= '';

          // Vault configuration. Used if database credentials are stored in Vault secrets manager.
          $DB['VAULT_URL']		= '';
          $DB['VAULT_DB_PATH']	= '';
          $DB['VAULT_TOKEN']		= '';

          // Use IEEE754 compatible value range for 64-bit Numeric (float) history values.
          // This option is enabled by default for new Zabbix installations.
          // For upgraded installations, please read database upgrade notes before enabling this option.
          $DB['DOUBLE_IEEE754']	= true;

          // Uncomment and set to desired values to override Zabbix hostname/IP and port.
          // $ZBX_SERVER			= '';
          // $ZBX_SERVER_PORT		= '';

          $ZBX_SERVER_NAME		= 'my-zabbix';

          $IMAGE_FORMAT_DEFAULT	= IMAGE_FORMAT_PNG;
 
  - name: Настраиваем PHP для работы Zabbix
    become: yes
    blockinfile:
       path: /etc/php/8.1/fpm/php.ini
       block: |
         post_max_size = 16M
         upload_max_filesize = 2M
         max_execution_time = 300
         max_input_time = 300
         memory_limit = 128M
         date.timezone = Europe/Moscow

 
  - name: Настроиваем  Nginx для работы с Zabbix
    blockinfile:
      path: /etc/nginx/conf.d/zabbix.conf
      block: |
          server {
              listen 80;
              server_name  {{ server_name }};

              root /usr/share/zabbix;

              index index.php index.html index.htm;

              location / {
                  try_files $uri $uri/ =404;
              }

              location ~ \.php$ {
                  fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  include fastcgi_params;
              }

              location ~ /\.ht {
                  deny all;
              }
          }

  - name: Перезапускаем сервисы Zabbix и Nginx
    become: yes
    systemd:
        name: "{{ item }}"
        state: restarted
        enabled: true  
    with_items:
        - zabbix-server
        - zabbix-agent
        - nginx
        - php8.1-fpm

  - name: Печать адреса сервера zabbix
    ansible.builtin.debug:
        msg: "Для работы с zabbix перейдите по адресу {{ zabbix_server_ip }} логин 'Admin' пароль 'zabbix'"







