- name: Установка Zabbix агента на сервера
  hosts: internal_servers
  gather_facts: no
  become: yes
  tasks:
    - name: Копируем zabbix пакет
      copy:
        src: packages/{{ pkg_zabbix }}
        dest: /tmp/

    - name: Устанавливаем zabbix репозиторий
      command: dpkg -i /tmp/{{ pkg_zabbix }}

    - name: Устанавливаем zabbix-agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: yes

    - name: Добавляем IP zabbix сервера
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server=127.0.0.1'
        replace: 'Server={{ zabbix_server }}'

    - name: Добавляем IP активного сервера
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'ServerActive=127.0.0.1'
        replace: 'ServerActive={{ zabbix_server }}'

    - name: Перезапускаем zabbix agent
      systemd:
        name: zabbix-agent
        state: restarted
        enabled: true   