- name: Configure zabbix agent to bastion
  hosts: bastion
  gather_facts: no
  become: yes
  tasks:
    - name: Copy zabbix package
      copy:
        src: packages/{{ pkg_zabbix }}
        dest: /tmp/

    - name: Install zabbix repository
      command: dpkg -i /tmp/{{ pkg_zabbix }}

    - name: Install zabbix-agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: yes

    - name: Add server IP
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'Server=127.0.0.1'
        replace: 'Server={{ zabbix_server }}'

    - name: Add server IP
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: 'ServerActive=127.0.0.1'
        replace: 'ServerActive={{ zabbix_server }}'

    - name: Restart zabbix agent
      systemd:
        name: zabbix-agent
        state: restarted
        enabled: true   